summary: Settings

sequence:

  - type: menu-title
    label: Game settings

  - type: menu-button
    condition: "!settings.playInFullScreen"
    icon: toggle-off.svg
    label: Full screen
    action:
      - type: settings-screen
        full: true
      - type: goto
        scene: settings

  - type: menu-button
    condition: settings.playInFullScreen
    label: Full screen
    icon: toggle-on.svg
    action:
      - type: settings-screen
        full: false
      - type: goto
        scene: settings

  - type: menu-button
    condition: "!settings.speakMessagesInVoice"
    label: Speak in voice
    icon: toggle-off.svg
    action:
      - type: settings-voice
        speak: true
      - type: goto
        scene: settings

  - type: menu-button
    condition: settings.speakMessagesInVoice
    label: Speak in voice
    icon: toggle-on.svg
    action:
      - type: settings-voice
        speak: false
      - type: goto
        scene: settings

  - type: menu-button
    label: Back
    scene: home
